-- Generated by Oracle SQL Developer Data Modeler 4.1.0.873
--   at:        2019-04-14 21:34:36 CEST
--   site:      SQL Server 2012
--   type:      SQL Server 2012




CREATE
  TABLE Artifact
  (
    id                      INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name                    VARCHAR (256) NOT NULL ,
    Workproduct_id          INTEGER NOT NULL ,
    Workproduct_Project_id  INTEGER NOT NULL ,
    Review_id               INTEGER ,
    Workproduct_Project_id1 INTEGER NOT NULL ,
    CONSTRAINT Artifact_PK PRIMARY KEY CLUSTERED (id, Workproduct_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Artifact_detail
  (
    id                              INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name                            VARCHAR (256) NOT NULL ,
    Detail_value                    VARCHAR (256) ,
    Artifact_id                     INTEGER NOT NULL ,
    Artifact_Workproduct_id         INTEGER NOT NULL ,
    Artifact_Workproduct_Project_id INTEGER NOT NULL ,
    CONSTRAINT Artifact_detail_PK PRIMARY KEY CLUSTERED (id, Artifact_id,
    Artifact_Workproduct_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Artifact_review
  (
    Artifact_id             INTEGER NOT NULL ,
    Artifact_Workproduct_id INTEGER NOT NULL ,
    Review_id               INTEGER NOT NULL ,
    CONSTRAINT Relation_24_PK PRIMARY KEY CLUSTERED (Artifact_id,
    Artifact_Workproduct_id, Review_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Header_Row
  (
    id                  INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name                VARCHAR (256) NOT NULL ,
    "function"          VARCHAR (50) ,
    parameter           VARCHAR (50) ,
    Review_tameplate_id INTEGER NOT NULL ,
    CONSTRAINT Header_Row_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Ibm_artifact
  (
    id                     INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    ibm_id                 INTEGER NOT NULL ,
    Name                   VARCHAR (256) NOT NULL ,
    Url                    VARCHAR (512) NOT NULL ,
    Workproduct_id         INTEGER NOT NULL ,
    Review_id              INTEGER ,
    Workproduct_Project_id INTEGER NOT NULL ,
    CONSTRAINT Ibm_artifact_PK PRIMARY KEY CLUSTERED (id, ibm_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Ibm_artifact_review
  (
    Ibm_artifact_id     INTEGER NOT NULL ,
    Ibm_artifact_ibm_id INTEGER NOT NULL ,
    Review_id           INTEGER NOT NULL ,
    CONSTRAINT Relation_23_PK PRIMARY KEY CLUSTERED (Ibm_artifact_id,
    Ibm_artifact_ibm_id, Review_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Project
  (
    id   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name VARCHAR (50) NOT NULL ,
    Description TEXT ,
    Project_type_id INTEGER NOT NULL ,
    Users_email     VARCHAR (50) NOT NULL ,
    CONSTRAINT Project_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Project_type
  (
    id   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name VARCHAR (50) NOT NULL ,
    CONSTRAINT Project_type_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Review
  (
    id         INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Start_date DATE NOT NULL ,
    Close_date DATE NOT NULL ,
    Name       VARCHAR (256) NOT NULL ,
    Description TEXT ,
    Workproduct_id         INTEGER NOT NULL ,
    Review_tameplate_id    INTEGER NOT NULL ,
    Workproduct_Project_id INTEGER NOT NULL ,
    Html TEXT ,
    CONSTRAINT Review_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Review_column
  (
    id   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name VARCHAR (256) NOT NULL ,
    Description TEXT ,
    type                VARCHAR (50) NOT NULL ,
    Review_tameplate_id INTEGER NOT NULL ,
    CONSTRAINT Review_column_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Review_column_type_enum
  (
    id               INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    name             VARCHAR (128) NOT NULL ,
    Review_column_id INTEGER ,
    CONSTRAINT Review_column_type_enum_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Review_role
  (
    id                  INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name                VARCHAR (50) NOT NULL ,
    Review_tameplate_id INTEGER NOT NULL ,
    CONSTRAINT Review_role_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Review_tameplate
  (
    id   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name VARCHAR (512) NOT NULL ,
    Description TEXT ,
    Users_email VARCHAR (50) NOT NULL ,
    CONSTRAINT Review_tameplate_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE System_role
  (
    id   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    name VARCHAR (30) NOT NULL ,
    CONSTRAINT System_role_PK PRIMARY KEY CLUSTERED (id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE User_Project
  (
    Users_email VARCHAR (50) NOT NULL ,
    Project_id  INTEGER NOT NULL ,
    CONSTRAINT Relation_3_PK PRIMARY KEY CLUSTERED (Users_email, Project_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE User_review_role
  (
    Users_email    VARCHAR (50) NOT NULL ,
    Review_id      INTEGER NOT NULL ,
    Review_role_id INTEGER NOT NULL ,
    CONSTRAINT User_review_PKv2 PRIMARY KEY CLUSTERED (Review_role_id,
    Users_email, Review_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Users
  (
    email          VARCHAR (50) NOT NULL ,
    password       VARCHAR (512) NOT NULL ,
    Firstname      VARCHAR (50) NOT NULL ,
    Lastname       VARCHAR (50) NOT NULL ,
    salt           VARCHAR (512) NOT NULL ,
    System_role_id INTEGER NOT NULL ,
    CONSTRAINT Users_PK PRIMARY KEY CLUSTERED (email)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

CREATE
  TABLE Workproduct
  (
    id   INTEGER NOT NULL IDENTITY NOT FOR REPLICATION ,
    Name VARCHAR (128) NOT NULL ,
    Description TEXT ,
    Artifacts_url VARCHAR (512) ,
    Project_id    INTEGER NOT NULL ,
    Users_email   VARCHAR (50) NOT NULL ,
    CONSTRAINT Workproduct_PK PRIMARY KEY CLUSTERED (id, Project_id)
WITH
  (
    ALLOW_PAGE_LOCKS = ON ,
    ALLOW_ROW_LOCKS  = ON
  )
  ON "default"
  )
  ON "default"
GO

ALTER TABLE Artifact
ADD CONSTRAINT Artifact_Review_FK FOREIGN KEY
(
Review_id
)
REFERENCES Review
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Artifact
ADD CONSTRAINT Artifact_Workproduct_FK FOREIGN KEY
(
Workproduct_id,
Workproduct_Project_id1
)
REFERENCES Workproduct
(
id ,
Project_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Artifact_detail
ADD CONSTRAINT Artifact_detail_Artifact_FK FOREIGN KEY
(
Artifact_id,
Artifact_Workproduct_id
)
REFERENCES Artifact
(
id ,
Workproduct_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE User_Project
ADD CONSTRAINT FK_ASS_16 FOREIGN KEY
(
Users_email
)
REFERENCES Users
(
email
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE User_Project
ADD CONSTRAINT FK_ASS_17 FOREIGN KEY
(
Project_id
)
REFERENCES Project
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE User_review_role
ADD CONSTRAINT FK_ASS_24 FOREIGN KEY
(
Users_email
)
REFERENCES Users
(
email
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE User_review_role
ADD CONSTRAINT FK_ASS_25 FOREIGN KEY
(
Review_id
)
REFERENCES Review
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Ibm_artifact_review
ADD CONSTRAINT FK_ASS_26 FOREIGN KEY
(
Ibm_artifact_id,
Ibm_artifact_ibm_id
)
REFERENCES Ibm_artifact
(
id ,
ibm_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Ibm_artifact_review
ADD CONSTRAINT FK_ASS_27 FOREIGN KEY
(
Review_id
)
REFERENCES Review
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Artifact_review
ADD CONSTRAINT FK_ASS_28 FOREIGN KEY
(
Artifact_id,
Artifact_Workproduct_id
)
REFERENCES Artifact
(
id ,
Workproduct_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Artifact_review
ADD CONSTRAINT FK_ASS_29 FOREIGN KEY
(
Review_id
)
REFERENCES Review
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Header_Row
ADD CONSTRAINT Header_Row_Review_column_FK FOREIGN KEY
(
id
)
REFERENCES Review_column
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Header_Row
ADD CONSTRAINT Header_Row_Review_tameplate_FK FOREIGN KEY
(
Review_tameplate_id
)
REFERENCES Review_tameplate
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Ibm_artifact
ADD CONSTRAINT Ibm_artifact_Review_FK FOREIGN KEY
(
Review_id
)
REFERENCES Review
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Ibm_artifact
ADD CONSTRAINT Ibm_artifact_Workproduct_FK FOREIGN KEY
(
Workproduct_id,
Workproduct_Project_id
)
REFERENCES Workproduct
(
id ,
Project_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Project
ADD CONSTRAINT Project_Project_type_FK FOREIGN KEY
(
Project_type_id
)
REFERENCES Project_type
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Project
ADD CONSTRAINT Project_Users_FK FOREIGN KEY
(
Users_email
)
REFERENCES Users
(
email
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Review
ADD CONSTRAINT Review_Review_tameplate_FK FOREIGN KEY
(
Review_tameplate_id
)
REFERENCES Review_tameplate
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Review
ADD CONSTRAINT Review_Workproduct_FK FOREIGN KEY
(
Workproduct_id,
Workproduct_Project_id
)
REFERENCES Workproduct
(
id ,
Project_id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Review_column
ADD CONSTRAINT Review_column_Review_tameplate_FK FOREIGN KEY
(
Review_tameplate_id
)
REFERENCES Review_tameplate
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Review_column_type_enum
ADD CONSTRAINT Review_column_type_enum_Review_column_FK FOREIGN KEY
(
Review_column_id
)
REFERENCES Review_column
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Review_role
ADD CONSTRAINT Review_role_Review_tameplate_FK FOREIGN KEY
(
Review_tameplate_id
)
REFERENCES Review_tameplate
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Review_tameplate
ADD CONSTRAINT Review_tameplate_Users_FK FOREIGN KEY
(
Users_email
)
REFERENCES Users
(
email
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE User_review_role
ADD CONSTRAINT User_review_Review_role_FK FOREIGN KEY
(
Review_role_id
)
REFERENCES Review_role
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Users
ADD CONSTRAINT Users_System_role_FK FOREIGN KEY
(
System_role_id
)
REFERENCES System_role
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Workproduct
ADD CONSTRAINT Workproduct_Project_FK FOREIGN KEY
(
Project_id
)
REFERENCES Project
(
id
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO

ALTER TABLE Workproduct
ADD CONSTRAINT Workproduct_Users_FK FOREIGN KEY
(
Users_email
)
REFERENCES Users
(
email
)
ON
DELETE
  NO ACTION ON
UPDATE NO ACTION
GO


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            18
-- CREATE INDEX                             0
-- ALTER TABLE                             27
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE DATABASE                          0
-- CREATE DEFAULT                           0
-- CREATE INDEX ON VIEW                     0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE ROLE                              0
-- CREATE RULE                              0
-- CREATE SCHEMA                            0
-- CREATE SEQUENCE                          0
-- CREATE PARTITION FUNCTION                0
-- CREATE PARTITION SCHEME                  0
-- 
-- DROP DATABASE                            0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


alter table dbo.header_row
add Review_column_id integer

alter table dbo.header_row
add foreign key (review_column_id) references dbo.review_column(id)

i/*nsert into dbo.System_Role values('Admin')
insert into dbo.System_Role values('User')


insert into dbo.Users values('jos@vsb.cz','2r6SCaYxTtpB6Ydfwv25aMk1t0wAiEymo62eesqulak=', 'Josef', 'Pohrom','vpUuiyQHz1wZoV9TgAT/Dw==', 2)
insert into dbo.Users values('michal@vsb.cz','oDtjiylrmjp+1HT5zK4++3GW7QQwOyqvVqf0+jXpKVo=', 'Michal', 'Prikryl','2vHLV303NPkOQuKHUjNB1g==', 2)

insert into dbo.Project_type values('Own project')
insert into dbo.Project_type values('IBM project')*/

alter table header_row
drop constraint review_column_id

alter table dbo.header_row
add constraint Header_row_review_column
foreign key (Review_column_id) references dbo.review_Column(id)
--select * from dbo.Header_Row
--select * from User_review_role

/*
update dbo.Header_row
set Name = 'soucet'
where id = 13*/
select * from dbo.Header_row